#include "pins.h"

#ifndef Light_Zones_h
#define Light_Zones_h

// Outer string lights
#define OUTER_STRING_LIGHTS_1 (BREAKOUT_PIN_9)
#define OUTER_STRING_LIGHTS_2 (BREAKOUT_PIN_10)
#define OUTER_STRING_LIGHTS_3 (BREAKOUT_PIN_11)
#define OUTER_STRING_LIGHTS_4 (BREAKOUT_PIN_12)
#define OUTER_STRING_LIGHTS_5 (BREAKOUT_PIN_13)
#define OUTER_STRING_LIGHTS_6 (BREAKOUT_PIN_14)
#define OUTER_STRING_LIGHTS_7 (BREAKOUT_PIN_15)
#define OUTER_STRING_LIGHTS_8 (BREAKOUT_PIN_16)
#define OUTER_STRING_LIGHTS_9 (BREAKOUT_PIN_17)
#define OUTER_STRING_LIGHTS_10 (BREAKOUT_PIN_18)
#define OUTER_STRING_LIGHTS_11 (BREAKOUT_PIN_19)
#define OUTER_STRING_LIGHTS_12 (BREAKOUT_PIN_20)
#define OUTER_STRING_LIGHTS_GROUP {OUTER_STRING_LIGHTS_1, OUTER_STRING_LIGHTS_2, OUTER_STRING_LIGHTS_3, OUTER_STRING_LIGHTS_4, OUTER_STRING_LIGHTS_5, OUTER_STRING_LIGHTS_6, OUTER_STRING_LIGHTS_7, OUTER_STRING_LIGHTS_8, OUTER_STRING_LIGHTS_9, OUTER_STRING_LIGHTS_10, OUTER_STRING_LIGHTS_11, OUTER_STRING_LIGHTS_12}

// Child's Rooms
#define CHILD_ROOM_1 (BREAKOUT_PIN_21)
#define CHILD_ROOM_2 (BREAKOUT_PIN_22)
#define CHILD_ROOM_3 (BREAKOUT_PIN_23)
#define CHILD_ROOM_GROUP {CHILD_ROOM_1, CHILD_ROOM_2, CHILD_ROOM_3}

// Family Room
#define FAMILY_ROOM_1 (BREAKOUT_PIN_24)
#define FAMILY_ROOM_2 (BREAKOUT_PIN_25)
#define FAMILY_ROOM_GROUP {FAMILY_ROOM_1, FAMILY_ROOM_2}

// Sitting Room
#define SITTING_ROOM (BREAKOUT_PIN_26)

// Dining Room
#define DINING_ROOM_1 (BREAKOUT_PIN_27)
#define DINING_ROOM_2 (BREAKOUT_PIN_28)
#define DINING_ROOM_GROUP {DINING_ROOM_1, DINING_ROOM_2}

// Bedroom
#define BEDROOM (BREAKOUT_PIN_29)

// Upstairs Hallway
#define UPSTAIRS_HALLWAY (BREAKOUT_PIN_30)

// Attic
#define ATTIC (BREAKOUT_PIN_31)

// All lights
#define ALL_LIGHTS_GROUP {OUTER_STRING_LIGHTS_1, OUTER_STRING_LIGHTS_2, OUTER_STRING_LIGHTS_3, OUTER_STRING_LIGHTS_4, OUTER_STRING_LIGHTS_5, OUTER_STRING_LIGHTS_6, OUTER_STRING_LIGHTS_7, OUTER_STRING_LIGHTS_8, OUTER_STRING_LIGHTS_9, OUTER_STRING_LIGHTS_10, OUTER_STRING_LIGHTS_11, OUTER_STRING_LIGHTS_12, CHILD_ROOM_1, CHILD_ROOM_2, CHILD_ROOM_3, FAMILY_ROOM_1, FAMILY_ROOM_2, SITTING_ROOM, DINING_ROOM_1, DINING_ROOM_2, BEDROOM, UPSTAIRS_HALLWAY, ATTIC}

#endif